/* Speech sounds are not spelling units: x=/k s/, qu=/k w/.
 * Auditory exercises use this explicit pronunciation lexicon. Unknown words
 * are excluded from sound-counting/manipulation, never guessed from letters. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.PokePhonics=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const ROWS={"pin":"p i n","pan":"p a n","map":"m a p","mop":"m o p","dog":"d aw g","pot":"p o t","cat":"k a t","cup":"k u p","duck":"d u k","sock":"s o k","sun":"s u n","ten":"t e n","pen":"p e n","hat":"h a t","hen":"h e n","bed":"b e d","bus":"b u s","leg":"l e g","bell":"b e l","fan":"f a n","log":"l aw g","bat":"b a t","van":"v a n","fox":"f o k s","box":"b o k s","six":"s i k s","web":"w e b","ship":"sh i p","fish":"f i sh","chip":"ch i p","ring":"r i ng","shell":"sh e l","shop":"sh o p","bath":"b a th","chick":"ch i k","frog":"f r o g","flag":"f l a g","drum":"d r u m","hand":"h a n d","milk":"m i l k","tent":"t e n t","nest":"n e s t","crab":"k r a b","clock":"k l o k","rain":"r ay n","tree":"t r ee","goat":"g oh t","boat":"b oh t","feet":"f ee t","sheep":"sh ee p","coat":"k oh t","train":"t r ay n","queen":"k w ee n","moon":"m oo n","book":"b uu k","star":"s t ar","car":"k ar","corn":"k or n","fork":"f or k","spoon":"s p oo n","shark":"sh ar k","foot":"f uu t","cake":"k ay k","bike":"b eye k","kite":"k eye t","snake":"s n ay k","five":"f eye v","plate":"p l ay t","home":"h oh m","bone":"b oh n","rose":"r oh z","nose":"n oh z","leaf":"l ee f","seal":"s ee l","cow":"k ow","owl":"ow l","coin":"k oy n","crown":"k r ow n","bird":"b er d","girl":"g er l","shirt":"sh er t","clown":"k l ow n","cap":"k a p","bug":"b u g","pig":"p i g","bee":"b ee","snail":"s n ay l","nail":"n ay l","lock":"l o k","cart":"k ar t","lake":"l ay k","sled":"s l e d","top":"t o p","spin":"s p i n","stop":"s t o p","brain":"b r ay n","farm":"f ar m","arm":"ar m","bread":"b r e d","red":"r e d","sea":"s ee","tin":"t i n","tap":"t a p","nap":"n a p","sit":"s i t","pit":"p i t","dot":"d o t","dig":"d i g","mat":"m a t","mad":"m a d","pod":"p o d","net":"n e t","nut":"n u t","rug":"r u g","kit":"k i t","cut":"k u t","rock":"r o k","run":"r u n","hug":"h u g","lip":"l i p","fun":"f u n","doll":"d o l","jam":"j a m","jet":"j e t","wig":"w i g","zip":"z i p","jug":"j u g","yes":"y e s","wax":"w a k s","king":"k i ng","chin":"ch i n","dish":"d i sh","moth":"m aw th","sing":"s i ng","jump":"j u m p","lamp":"l a m p","plant":"p l a n t","grass":"g r a s","sail":"s ay l","road":"r oh d","soap":"s oh p","seed":"s ee d","toad":"t oh d","food":"f oo d","horn":"h or n","barn":"b ar n","gate":"g ay t","time":"t eye m","cave":"k ay v","smile":"s m eye l","flame":"f l ay m","note":"n oh t","stone":"s t oh n","cube":"k y oo b","tube":"t oo b","meat":"m ee t","globe":"g l oh b","down":"d ow n","soil":"s oy l","burn":"b er n","boil":"b oy l","night":"n eye t","light":"l eye t","ear":"ear","beard":"b ear d","hair":"h air","chair":"ch air","fight":"f eye t","day":"d ay","play":"p l ay","hay":"h ay","cloud":"k l ow d","couch":"k ow ch","pie":"p eye","tie":"t eye","toy":"t oy","boy":"b oy","blue":"b l oo","saw":"s aw","straw":"s t r aw","screw":"s k r oo","whale":"w ay l","phone":"f oh n","paw":"p aw"};
const SPELL_AUDIO={a:'a',e:'e',i:'i',o:'o',u:'u',c:'k',k:'k',ck:'k',x:['k','s'],qu:['k','w'],ll:'l',ss:'s',ff:'f',zz:'z',ai:'ay',ay:'ay',ee:'ee',ea:'ee',oa:'oh',oo:'oo',ow:'ow',oi:'oy',oy:'oy',ir:'er',ur:'er',ar:'ar',or:'or',er:'er',a_e:'ay',i_e:'eye',o_e:'oh',u_e:['y','oo'],igh:'eye',ear:'ear',air:'air',ou:'ow',ie:'eye',ue:'oo',aw:'aw',ew:['y','oo'],wh:'w',ph:'f'};
const parts=w=>(ROWS[String(w).toLowerCase()]||'').split(' ').filter(Boolean).map(g=>({g,play:g,audio:g,cls:['a','e','i','o','u','ay','ee','oh','oo','uu','ar','or','er','eye','ow','oy','aw','ear','air'].includes(g)?'vowel':'cons'}));
function annotate(word,spelling){const phones=parts(word);if(!phones.length)return spelling;let at=0;return spelling.map((p,i)=>{if(p.cls==='silent')return p;const left=spelling.slice(i).filter(x=>x.cls!=='silent').length;const flexible=['x','qu','u','u_e','ew'].includes(p.play||p.g);const count=flexible&&phones.length-at>left?2:1;const sounds=phones.slice(at,at+count).map(x=>x.g);at+=count;return {...p,audio:sounds.length===1?sounds[0]:sounds};});}

const audioKeys=p=>{const key=typeof p==='string'?p:(p.audio||p.play||p.g);const value=Array.isArray(key)?key:SPELL_AUDIO[key]||key;return Array.isArray(value)?value:[value];};
const clips=["a", "e", "i", "o", "u", "uu", "ee", "oo", "ay", "oh", "eye", "ow", "oy", "aw", "ar", "or", "er", "ear", "air", "b", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "r", "s", "t", "v", "w", "y", "z", "sh", "ch", "th", "dh", "ng", "zh"];
const clipKeys=p=>audioKeys(p).flatMap(k=>({ing:['i','ng'],id:['i','d']}[k]||[k]));
// Phoneme counts still use clipKeys. Playback can use one complete recording
// for qu=/k w/ and x=/k s/, avoiding a splice between their two sounds.
const recordedClips=['a','e','i','o','u','b','d','f','g','h','j','k','l','m','n','p','r','s','t','v','w','y','z','sh','ch','ng','qu','x'];
function clipFiles(p){
 const keys=clipKeys(p),joined=keys.join(' '),whole=joined==='k w'?'qu':joined==='k s'?'x':null;
 if(whole)return ['assets/phonemes/recorded-v82/'+whole+'.wav'];
 return keys.map(k=>'assets/phonemes/'+(recordedClips.includes(k)?'recorded-v82/':'female-v81/')+k+'.wav');
}
return {clips,clipKeys,clipFiles,recordedClips,ROWS,parts,has:w=>!!ROWS[String(w).toLowerCase()],annotate,audioKeys};
});
