const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),M=require('../drive-mirror.js');
const sample=()=>({sessions:{s1:{id:'s1',rev:2,days:{'2026-09-27':{practiceMs:1200}},questions:{q:{id:'q',expected:3}}}},settings:{goalMinutes:15,secret:'excluded'},lastCloudSyncAt:100});
const url='https://script.google.com/macros/s/EXAMPLE/exec',secret='a'.repeat(48);
function harness(request=async()=>({type:'opaque',ok:false})){const d={},timers=[];let status;const c=M.create({snapshot:sample,storage:{getItem:k=>d[k],setItem:(k,v)=>d[k]=v},request,setTimer:f=>{timers.push(f);return timers.length;},clearTimer(){},onStatus:s=>status=s});return {c,d,timers,get status(){return status;}};}
test('backup excludes credentials and uses a stable session revision signature',()=>{const b=M.backup({...sample(),url,secret});assert.equal(b.app,'PokéMath learning');assert.ok(!JSON.stringify(b).includes('excluded'));assert.ok(!('secret'in b));assert.equal(M.signature(b),M.signature({...b,exportedAt:'2099-01-01T00:00:00Z'}));const newer=structuredClone(b);newer.sessions.s1.rev++;assert.notEqual(M.signature(b),M.signature(newer));});
test('mirror is off until explicitly configured with an Apps Script exec URL',async()=>{let calls=0;const h=harness(async()=>{calls++;});await h.c.send();assert.equal(calls,0);for(const endpoint of ['https://evil.example/exec',url+'?secret=x','http://script.google.com/macros/s/X/exec',url.replace('/exec','/dev')])assert.throws(()=>h.c.saveConfig({url:endpoint,secret,enabled:true}));assert.equal(calls,0);});
test('automatic scheduling is bounded even while five-second autosaves continue',()=>{const h=harness();h.c.saveConfig({url,secret,enabled:true});for(let i=0;i<50;i++)h.c.schedule();assert.equal(h.timers.length,1);});
test('opaque POST never claims a confirmed upload, excludes credentials from backup and deduplicates unchanged snapshots',async()=>{let calls=0;const h=harness(async(u,o)=>{calls++;assert.equal(u,url);assert.equal(o.mode,'no-cors');const body=JSON.parse(o.body);assert.equal(body.secret,secret);assert.ok(!JSON.stringify(body.backup).includes(secret));return {type:'opaque',ok:false};});h.c.saveConfig({url,secret,enabled:true});assert.equal(await h.c.send('auto'),true);assert.match(h.status,/Delivery is not confirmed/);assert.equal(await h.c.send('auto'),false);assert.equal(calls,1);});
test('network failure retains pending revisions and allows a retry',async()=>{let calls=0;const h=harness(async()=>{if(++calls===1)throw Error('offline');return {type:'opaque'};});h.c.saveConfig({url,secret,enabled:true});assert.equal(await h.c.send('auto'),false);assert.equal(await h.c.send('auto'),true);assert.equal(calls,2);});
function relay(){const files=new Map(),calls=[];const props={MIRROR_SECRET:secret,MIRROR_FOLDER_ID:'private-folder'};const f={getFilesByName(name){let used=false;return{hasNext:()=>!used&&files.has(name),next:()=>{used=true;return {getBlob:()=>({getDataAsString:()=>files.get(name)}),setContent:v=>files.set(name,v)}}};},createFile:(n,t)=>files.set(n,t)};const ctx={PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]})},DriveApp:{getFolderById:id=>{calls.push(id);return f;}},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},Utilities:{formatDate:()=> '2026-09-27'},MimeType:{PLAIN_TEXT:'text/plain'},ContentService:{MimeType:{JSON:'json'},createTextOutput:t=>({setMimeType:()=>JSON.parse(t)})},Date};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../tools/family-drive-mirror.gs'),'utf8'),ctx);return {ctx,files,calls,post:(backup,s=secret)=>ctx.doPost({postData:{contents:JSON.stringify({secret:s,backup})}})};}
test('relay preserves Euna backup names and rejects unauthorized or wrong app payloads before touching Drive',()=>{const r=relay(),b={app:'Mochi learning',version:1,anything:'unchanged'};assert.equal(r.post(b,'wrong').ok,false);assert.equal(r.post({app:'unrelated',version:1}).ok,false);assert.equal(r.calls.length,0);assert.equal(r.post(b).ok,true);assert.deepEqual(JSON.parse(r.files.get('euna-mochi-latest.json')),b);assert.ok(r.files.has('euna-mochi-2026-W39.json'));assert.ok(!r.files.has('jonah-pokemath-latest.json'));});
test('late and duplicate Jonah snapshots never erase or lower existing session revisions',()=>{const r=relay(),b=M.backup({...sample(),exportedAt:'2026-09-28T01:00:00Z'});assert.equal(r.post(b).ok,true);const late=structuredClone(b);late.exportedAt='2026-09-27T00:00:00Z';late.sessions.s1.rev=1;late.sessions.s1.questions={};late.sessions.s2={id:'s2',rev:1,days:{},questions:{}};r.post(late);r.post(late);const merged=JSON.parse(r.files.get('jonah-pokemath-latest.json'));assert.equal(merged.sessions.s1.rev,2);assert.ok(merged.sessions.s1.questions.q);assert.ok(merged.sessions.s2);assert.equal(merged.exportedAt,b.exportedAt);assert.ok(merged.receivedAt);assert.ok(r.files.has('jonah-pokemath-2026-W39.json'));});
test('malformed Jonah records or corrupt existing JSON leave the existing mirror untouched',()=>{const r=relay(),b=M.backup(sample());r.post(b);const before=r.files.get('jonah-pokemath-latest.json');b.sessions.s1.id='different';assert.equal(r.post(b).ok,false);assert.equal(r.files.get('jonah-pokemath-latest.json'),before);r.files.set('jonah-pokemath-latest.json','broken JSON');assert.equal(r.post(M.backup(sample())).ok,false);assert.equal(r.files.get('jonah-pokemath-latest.json'),'broken JSON');});
