const {test}=require('node:test'),assert=require('node:assert/strict'),F=require('../foundations.js'),C=require('../learning-core.js');
const sessions=qs=>({test:{id:'test',rev:1,days:{},questions:Object.fromEntries(qs.map((q,i)=>[i,q]))}});
function history(skill,n,extra={}){return Array.from({length:n},(_,i)=>({...F.make(skill,{...F.plan(skill,{}),recent:[]},()=>i%5/5),id:String(i),day:'2026-09-27',startedAt:i*1000,completedAt:i*1000+900,responses:[{correct:true}],firstResponseMs:30000,...extra}));}
test('Play mixes 60% part-whole/subtraction, 25% addition/patterns and 15% equal groups',()=>{const a=Array.from({length:20},(_,i)=>F.skillAt(i));assert.equal(a.filter(x=>['split','take','missing','undo','predict'].includes(x)).length,12);assert.equal(a.filter(x=>['add','patterns'].includes(x)).length,5);assert.equal(a.filter(x=>x==='groups').length,3);assert.equal(F.skillAt(20),a[0]);});
test('all generated relationships and equal groups stay within their declared range including zero subtraction',()=>{for(const skill of Object.keys(F.labels))for(const p of F.stages(skill))for(let i=0;i<100;i++){const t=F.make(skill,p,()=>i/100);assert.ok(t.expected>=0&&t.expected<=p.range);assert.ok(t.b<=t.a||skill==='groups');assert.equal(t.expected,skill==='groups'?t.a*t.b:skill==='missing'?t.b:skill==='undo'?t.a:t.a-t.b);}});
test('mastery is specific to the relationship and cannot transfer from visible counting or extra help',()=>{const qs=history('split',6);assert.equal(F.plan('split',sessions(qs)).level,1);assert.equal(F.plan('predict',sessions(qs)).level,0);for(const extra of [{helped:true},{support:'pictures'},{a:5,b:2,expected:3}])assert.equal(F.plan('split',sessions(history('split',6,extra))).level,0);});
test('repeated difficulty restores small groups after promotion',()=>{const qs=history('split',6);qs.push(...history('split',5,{level:1,range:10,helped:true}).map((q,i)=>({...q,startedAt:10000+i*1000,completedAt:10900+i*1000})));assert.equal(F.plan('split',sessions(qs)).level,0);});
test('daily report gives honest denominators, sample thresholds, sync freshness and visual support caveat',()=>{const qs=history('missing',2);qs[0].helped=true;const s=F.dailyReport(sessions(qs),'2026-09-27',0,true);assert.match(s,/1\/2 \(50%\)/);assert.match(s,/too little data/);assert.match(s,/No confirmed cloud upload/);assert.match(s,/not proof of mental arithmetic/);assert.match(s,/waiting to sync/);assert.match(F.dailyReport({},'2026-09-27'),/does not prove no practice/);});
// Exercise the real UI handlers with an in-memory DOM and tracker. No child records or cloud connection.
const fs=require('node:fs'),vm=require('node:vm');
function harness(){
 class El{constructor(tag='div'){this.tag=tag;this.children=[];this.classList={add(){}};this.attrs={};this.disabled=false;this.textContent='';}append(...x){this.children.push(...x);}appendChild(x){this.append(x);}after(){}replaceChildren(...x){this.children=x;}setAttribute(k,v){this.attrs[k]=v;}remove(){}click(){if(!this.disabled)this.onclick?.();}set innerHTML(s){this.html=s;}get innerHTML(){return this.html;}}
 const els={},data={},t=new C.Tracker(),answers=[],helps=[];let paused=false;
 const ctx={PokeFoundations:F,PokeVisuals:{icon:()=>''},document:{createElement:tag=>new El(tag),getElementById:id=>els[id]||=(new El())},localStorage:{setItem:(k,v)=>data[k]=v,getItem:k=>data[k]||null,removeItem:k=>delete data[k]},screens:{},mode:'home',soundOn:true,safeArt:()=>'',pickMon:()=>25,say(){},show(){},sndGood(){},addStar(){},readyForNext:()=>true,newQuestion(){},Date,adventure:{beforeQuestion:()=>true,isPaused:()=>paused,tracker:t,begin:(q,ref)=>t.begin(q,ref),respond:(v,c)=>{answers.push({v,c});t.answer(v,c);},help:k=>{helps.push(k);t.help(k);}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../foundation-ui.js'),'utf8')+'\nvar ui=createFoundations();',ctx);
 const all=e=>[e,...e.children.flatMap(all)],find=label=>all(els.foundationActions).find(e=>e.attrs?.['aria-label']===label);
 return {ctx,els,t,answers,helps,data,all,find,pause:v=>paused=v};
}
test('construction error plus visual help remains helped, never independent, and resumes the same question',()=>{const h=harness();h.ctx.ui.start('groups');const q=h.t.question();h.find('Check my groups').click();assert.equal(h.answers[0].c,false);h.find('Show me with pictures').click();assert.ok(q.helped);h.ctx.ui.start('groups');assert.equal(h.t.question().id,q.id);h.find('Answer '+q.expected).click();assert.equal(C.allQuestions(h.t.sessions).length,1);assert.equal(C.independent(q),false);assert.ok(h.find('Next question'));});
test('predict step shows a whole first and a cover until response, pauses all answer actions',()=>{const h=harness();h.ctx.ui.start('predict');const q=h.t.question();assert.equal(h.find('Answer '+q.expected),undefined);h.find('Predict before checking').click();assert.ok(h.all(h.els.foundationBoard).some(e=>e.className==='foundation-cover'));h.pause(true);h.find('Answer '+q.expected).click();assert.equal(h.answers.length,0);h.pause(false);h.find('Answer '+q.expected).click();assert.equal(h.answers[0].c,true);assert.ok(!h.all(h.els.foundationBoard).some(e=>e.className==='foundation-cover'));});
test('every foundation activity renders and completes through picture help with supported credit',()=>{for(const skill of Object.keys(F.labels)){const h=harness();h.ctx.ui.start(skill);const q=h.t.question();h.find('Show me with pictures').click();h.find('Answer '+q.expected).click();assert.ok(q.completedAt,skill);assert.equal(C.independent(q),false,skill);}});
