const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../learning-core.js');
function clock(){let now=Date.parse('2026-09-17T15:00:00Z'),seq=0;const t=new C.Tracker({now:()=>now,id:()=>String(++seq)});return {t,step(ms=1000){now+=ms;t.tick();},set(ms){now=ms;},now:()=>now};}
const meta={section:'add',skill:'add',a:1,b:4,expected:5,range:5,support:'pictures',format:'result',level:0};
test('home, collections, rewards and hidden pages do not count as practice',()=>{const {t,step}=clock();step();t.setSection('team');step();t.setSection('add');t.begin(meta);step();t.setBlocked(true);step();t.setBlocked(false);t.setVisible(false);step();t.setVisible(true);step();const s=C.summarize(t.sessions,'2026-09-17');assert.equal(s.practiceMs,2000);assert.equal(s.collectionMs,1000);assert.equal(s.foregroundMs,5000);});
test('thinking counts up to 60 seconds, ordinary taps cannot silently unpause',()=>{const {t,step}=clock();t.begin(meta);for(let i=0;i<90;i++)step();assert.equal(t.question().activeMs,60000);assert.equal(t.idle,true);t.interact();step();assert.equal(t.question().activeMs,60000);t.resume();step();assert.equal(t.question().activeMs,61000);});
test('a suspended process never backfills sleeping time',()=>{const {t,step}=clock();t.begin(meta);step();step(120000);assert.equal(t.question().activeMs,1000);});
test('answers after help are supported successes, never independent mastery',()=>{const {t,step}=clock();t.begin(meta);step();t.help('pictures');step();t.answer(5,true);const s=C.summarize(t.sessions,'2026-09-17');assert.equal(s.completed,1);assert.equal(s.independent,0);assert.equal(s.helped,1);assert.equal(s.medianMs,null);});
test('resuming a question preserves first response, help and accumulated active duration',()=>{const {t,step}=clock();const ref=t.begin(meta);step();t.answer(3,false);t.help('guided');t.setSection('home');step(5000);t.setSection('add');t.begin(meta,ref);step();t.answer(5,true);const q=C.allQuestions(t.sessions)[0];assert.equal(q.activeMs,2000);assert.equal(q.responses[0].value,3);assert.equal(q.firstResponseMs,1000);assert.equal(q.helped,true);assert.equal(C.allQuestions(t.sessions).length,1);});
function record(i,day='2026-09-17',extra={}){const a=1+i%4,b=5-a;return {...meta,id:String(i),a,b,day,startedAt:Date.parse(day+'T16:00:00Z')+i*2000,completedAt:Date.parse(day+'T16:00:01Z')+i*2000,responses:[{value:5,correct:true}],firstResponseMs:25000,...extra};}
const sessions=qs=>({s:{id:'s',rev:1,days:{},questions:Object.fromEntries(qs.map((q,i)=>[i,q]))}});
test('slow independent success can progress but only after distinct later-day retention checks',()=>{const qs=Array.from({length:10},(_,i)=>record(i));assert.equal(C.planFor('add','add',sessions(qs)).level,0);assert.equal(C.planFor('add','add',sessions(qs)).readyDay,'2026-09-17');qs.push(...[10,11,12].map(i=>record(i,'2026-09-18')));const p=C.planFor('add','add',sessions(qs));assert.equal(p.level,1);assert.equal(p.range,5);assert.equal(p.support,'numbers');});
test('repeated identical facts or helped answers cannot unlock a new level',()=>{const qs=Array.from({length:10},(_,i)=>record(i,'2026-09-17',{a:1,b:4}));assert.equal(C.planFor('add','add',sessions(qs)).readyDay,null);const helped=Array.from({length:10},(_,i)=>record(i,'2026-09-17',{helped:true}));assert.equal(C.planFor('add','add',sessions(helped)).readyDay,null);});
test('three failures in five at the current level restore one support step',()=>{const qs=Array.from({length:10},(_,i)=>record(i));qs.push(...[10,11,12].map(i=>record(i,'2026-09-18')));qs.push(...[13,14,15,16,17].map(i=>record(i,'2026-09-18',{level:1,support:'numbers',helped:i>14})));assert.equal(C.planFor('add','add',sessions(qs)).level,0);});
test('dashboard comparisons keep representations and levels separate and require samples',()=>{const a=C.summarize(sessions([record(1)]),'2026-09-17');const b=C.summarize(sessions(Array.from({length:10},(_,i)=>record(i,'2026-09-16',{range:10}))),'2026-09-16');assert.equal(C.comparisons(a,b)[0].accuracyChange,null);assert.equal(C.comparisons(a,b)[0].previousN,0);});
test('replayed session snapshots are idempotent and older snapshots cannot erase updates',()=>{const {t,step}=clock();t.begin(meta);step();t.answer(5,true);const copy=structuredClone(t.sessions);t.merge(copy);t.merge(copy);assert.equal(C.summarize(t.sessions,'2026-09-17').attempted,1);copy[t.sessionId].rev=0;copy[t.sessionId].questions={};t.merge(copy);assert.equal(C.allQuestions(t.sessions).length,1);});
test('Madison calendar dates and rolling periods handle DST without a fixed UTC offset',()=>{assert.equal(C.dayKey(Date.parse('2026-03-08T05:30:00Z')),'2026-03-07');assert.equal(C.dayKey(Date.parse('2026-03-09T05:30:00Z')),'2026-03-09');assert.equal(C.shiftDay('2026-03-01',-1),'2026-02-28');});

test('active time is split accurately across midnight in Madison',()=>{let now=Date.parse('2026-09-18T04:59:59.000Z'),i=0;const t=new C.Tracker({now:()=>now,id:()=>String(++i)});t.begin(meta);now+=2000;t.tick();assert.equal(C.summarize(t.sessions,'2026-09-17').practiceMs,1000);assert.equal(C.summarize(t.sessions,'2026-09-18').practiceMs,1000);});
test('returning after a five-minute break creates a new session for fatigue comparisons',()=>{const {t,step}=clock();t.begin(meta);step();t.answer(5,true);const original=t.sessionId;t.setSection('home');step(301000);t.begin(meta);assert.notEqual(t.sessionId,original);});
