const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const Core=require('../nightly-priority-core.js'),N=require('../nightly-plan.js'),C=require('../learning-core.js'),R=require('../reading-core.js'),D=require('../reading-data.js'),Daily=require('../reading-daily.js'),M=require('../math-path-core.js'),Tutor=require('../reading-tutor.js'),Mirror=require('../drive-mirror.js'),A=require('../reading-art.js');
const NOW=Date.parse('2026-10-08T12:00:00Z'),day=Core.day(NOW),copy=x=>JSON.parse(JSON.stringify(x));
const words=new Set(D.ROUTES.flatMap(r=>[...r.blend,...r.build]).concat(Daily.ACTIONS).map(R.clean).filter(A.has));
const catalog={maths:id=>!!M.BY[id]&&!M.BY[id].delegate,sound:id=>!!D.G[id],word:id=>words.has(id)};
function plan(){return {schema:1,id:'jonah-nightly-2026-10-08',revision:1,student:'Jonah',timeZone:'America/Chicago',reviewedDate:'2026-10-07',sessionDate:day,generatedAt:'2026-10-08T05:10:00Z',sourceExportedAt:'2026-10-08T01:00:00Z',subjects:{reading:{focus:'Blend sounds into a word.',sounds:['a'],words:['pin']},maths:{focus:'Compare small numbers.',skills:['compare10']}}};}
function env(){let p=plan(),now=NOW,response=null,c={url:'https://script.google.com/macros/s/SYNTHETIC/exec',secret:'synthetic-secret-at-least-24-characters',enabled:true};const values=new Map(),requests=[];const client=Core.create({student:'Jonah',catalog,config:()=>c,storage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},key:'test-jonah',request:async(u,o)=>{requests.push({u,o});return response||{ok:true,type:'cors',text:async()=>JSON.stringify({ok:true,service:'family-learning-mirror',planApi:1,student:'Jonah',plan:p})};},hash:async t=>crypto.createHash('sha256').update(t).digest('hex'),now:()=>now});return {client,values,requests,setPlan:v=>p=v,setResponse:v=>response=v,setNow:v=>now=v,setConfig:v=>c=v};}
test('Jonah schema accepts authored targets and rejects wrong child, unknown IDs, arbitrary commands, scores and durations',()=>{assert.deepEqual(Core.validate(plan(),'Jonah',catalog,NOW),plan());for(const mutate of [p=>p.student='Hana',p=>p.subjects.reading.words=['inventedword'],p=>p.subjects.reading.sounds=['zzz'],p=>p.subjects.maths.skills=['nonexistent'],p=>p.subjects.reading.minutes=25,p=>p.subjects.maths.reward=100,p=>p.subjects.reading.focus='<img>',p=>p.subjects.reading.words=Array(4).fill('pin'),p=>delete p.subjects.reading]){const p=plan();mutate(p);assert.throws(()=>Core.validate(p,'Jonah',catalog,NOW));}});
test('Jonah receiver verifies its own envelope, adopts only at boundaries and blocks disconnected cached data',async()=>{const e=env();await e.client.refresh(true);assert.equal(e.requests.length,1);assert.equal(JSON.parse(e.requests[0].o.body).action,'readJonahNextSession');assert.equal(e.client.plan(),null);assert.equal(e.client.adopt().student,'Jonah');const p=plan();p.revision=2;e.setPlan(p);await e.client.refresh(true);assert.equal(e.client.plan().revision,1);assert.equal(e.client.adopt().revision,2);e.setConfig({});assert.equal(e.client.plan(),null);assert.equal(e.client.report().active,null);assert(!JSON.stringify([...e.values]).includes('synthetic-secret'));});
for(const issue of ['cross-child','opaque','html','expired','future'])test('Jonah '+issue+' never becomes a usable current plan',async()=>{const e=env();if(issue==='cross-child')e.setResponse({ok:true,text:async()=>JSON.stringify({ok:true,service:'family-learning-mirror',student:'Hana',planApi:1,plan:plan()})});if(issue==='opaque')e.setResponse({ok:true,type:'opaque'});if(issue==='html')e.setResponse({ok:true,text:async()=>'<html>'});if(issue==='expired')e.setNow(NOW+86400000);if(issue==='future'){const p=plan();p.sessionDate='2026-10-09';e.setPlan(p);}await e.client.refresh(true);assert.equal(e.client.adopt(),null);});
test('sound priority chooses a real eligible buddy without changing the four stages or target time',()=>{const s=R.freshState(),before=JSON.stringify(s),status={day,cycle:0,stage:Daily.STAGES[0]},r=N.readingRound({},s,status,plan(),Daily,()=>.4,NOW);assert(r.items.some(it=>it.nightlyTarget==='sound:a'));assert(r.items.every(it=>!it.nightlyPlan||it.nightlyPlan.planId===plan().id));assert.equal(r.daily.stage,'sounds');assert.equal(Daily.progress({},day).target,720000);assert.equal(JSON.stringify(s),before);assert.deepEqual(Daily.STAGES.map(s=>s.minutes),[2,4,3,3]);});
test('word priorities affect actual selection and keep explicit teaching; unknown-route words cannot be injected',()=>{const s=R.freshState(),status={day,cycle:0,stage:Daily.STAGES[1]};const r=N.readingRound({},s,status,plan(),Daily,()=>.2,NOW);assert.equal(r.items.find(x=>x.word)?.word,'pin');assert(r.items.some(x=>x.nightlyTarget==='word:pin'));assert(r.items.filter(x=>x.word==='pin').every(x=>x.teach));const p=plan();p.subjects.reading.words=['smile'];const advanced=N.readingRound({},s,status,p,Daily,()=>.2,NOW);assert(!advanced.items.some(x=>x.word==='smile'));});
test('selected target is not repeatedly prioritised after an earlier block, including revision changes',()=>{const sessions={s:{id:'s',rev:1,questions:{q:{id:'q',section:'read',dailyVersion:1,dailyDay:day,dailyCycle:0,dailyStage:'words',nightlyTarget:'word:pin',startedAt:NOW,completedAt:NOW,word:'pin',teach:true,responses:[]}}}};const p=plan();p.revision=2;const r=N.readingRound(sessions,R.freshState(),{day,cycle:0,stage:Daily.STAGES[1]},p,Daily,()=>.4,NOW);assert(!r.items.some(x=>x.nightlyTarget==='word:pin'));});
test('story selection and read-and-act prerequisite teaching retain normal behavior',()=>{for(const stage of [Daily.STAGES[2],Daily.STAGES[3]]){const s=R.freshState(),status={day,cycle:0,stage};const a=N.readingRound({},s,status,plan(),Daily,()=>.3,NOW),b=Daily.round({},s,status,()=>.3);assert.deepEqual(a,b);}});
test('math priorities change an eligible task but cannot bypass checks, foundations, locks or due review',()=>{const base={type:'path',skill:'numeral10'},s=M.freshState(),p=plan();assert.equal(N.mathRoute(base,p,{},s,M,C,NOW).skill,'compare10');for(const b of [{type:'check'},{type:'foundation',skill:'take'},{type:'quiz',mode:'sub'},{...base,review:true}])assert.deepEqual(N.mathRoute(b,p,{},s,M,C,NOW),b);p.subjects.maths.skills=['tensones'];assert.deepEqual(N.mathRoute(base,p,{},s,M,C,NOW),base);p.subjects.maths.skills=['compare10'];assert.deepEqual(N.mathRoute(base,p,{},s,M,C,NOW,['numeral10']),base);});
test('math priorities have a two-skill daily budget; same-date revision does not reset use',()=>{const p=plan(),sessions={s:{id:'s',rev:1,questions:{a:{id:'a',section:'path',skill:'compare10',nightlyPlan:Core.identity(p),startedAt:NOW},b:{id:'b',section:'path',skill:'numeral10',nightlyPlan:Core.identity(p),startedAt:NOW}}}};p.revision=2;const base={type:'path',skill:'numeral10'};assert.deepEqual(N.mathRoute(base,p,sessions,M.freshState(),M,C,NOW),base);});
test('tracker and existing mirror retain answer provenance and receipts without changing assistance, old sessions or collection',()=>{const t=new C.Tracker({now:()=>NOW}),prior={id:'old',rev:8,questions:{q:{id:'q',correct:true}},days:{}};t.sessions.old=copy(prior);const original=JSON.stringify(prior),round=N.readingRound({},R.freshState(),{day,cycle:0,stage:Daily.STAGES[1]},plan(),Daily,()=>.2,NOW),prepared=Tutor.prepare(round,{}),it=prepared.items.find(x=>x.nightlyPlan);t.begin({section:'read',...it});t.help('guided practice');const answered=t.question();t.answer(it.answer,true);assert.equal(C.independent(answered),false);const slot=t.sessions[t.sessionId];slot.learningState={nightlyPlan:{updatedAt:NOW,state:{schema:1,student:'Jonah',active:Core.identity(plan())}}};const b=Mirror.backup({sessions:t.sessions});assert.deepEqual(b.sessions.old,prior);assert.equal(JSON.stringify(prior),original);assert.equal(b.sessions[t.sessionId].learningState.nightlyPlan.state.student,'Jonah');assert.equal(b.sessions[t.sessionId].questions[answered.id].nightlyPlan.planId,plan().id);});
