'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test'),crypto=require('node:crypto');
const path=require('node:path'),root=__dirname;
const original=fs.readFileSync(path.join(root,'family-original.gs'),'utf8');
const corrected=fs.readFileSync(path.join(root,'../family-drive-mirror.gs'),'utf8');
const eunaOnly=fs.readFileSync(path.join(root,'euna-only-v7.7.0.gs'),'utf8');
const NOW=Date.parse('2026-10-08T12:00:00.000Z'),SECRET='synthetic-test-secret-not-a-real-credential';
const clone=x=>JSON.parse(JSON.stringify(x));
function plan(){return {schema:1,id:'synthetic-plan-2026-10-08',revision:1,student:'Euna',timeZone:'America/Chicago',reviewedDate:'2026-10-07',sessionDate:'2026-10-08',generatedAt:'2026-10-08T05:10:00.000Z',sourceExportedAt:'2026-10-08T01:00:00.000Z',subjects:{maths:{focus:'Identify the requested faces.',steps:[{kind:'lesson',unit:'geo-face-pairs'},{kind:'practice',unit:'geo-face-pairs',phase:'guided',count:1},{kind:'practice',unit:'geo-face-pairs',phase:'apply',count:2}]},science:{focus:'Change one factor at a time.',steps:[{kind:'lesson',unit:'fairtest'},{kind:'practice',unit:'fairtest',phase:'apply',count:1}]}}};}
function backups(){return {
 Euna:{app:'Mochi learning',version:1,exported:'2026-10-08T01:00:00.000Z',learning:{attempts:[{id:'synthetic-math-1',firstCorrect:false,help:true}]},nightlyPlanReview:{planId:'synthetic-previous-plan',revision:1},state:{cats:['synthetic-cat'],coins:7}},
 Hana:{app:'Hana learning',schemaVersion:1,appVersion:'test',exportedAt:NOW-10000,exportedAtISO:new Date(NOW-10000).toISOString(),timeZone:'America/Chicago',learning:{events:[{id:'synthetic-h-1'}],checks:[]},skills:[],next:[],periods:{},limits:{},credentials:'synthetic-field-must-not-be-exported'},
 Jonah:{app:'PokéMath learning',version:1,schema:1,build:85,child:'Jonah',exportedAt:'2026-10-08T01:00:00.000Z',lastCloudSyncAt:11,settings:{goalMinutes:12},sessions:{synthetic1:{id:'synthetic1',rev:2,days:{'2026-10-07':{activeMs:15000}},questions:{q1:{correct:true}}}},credentials:'synthetic-field-must-not-be-exported'}
};}
function env(source,{props={},separate=true,busy=false,text=JSON.stringify(plan()),sharing='PRIVATE',trashed=false,mime='document',docsError=false,now=NOW}={}){
 const values={MIRROR_SECRET:SECRET,MIRROR_FOLDER_ID:'fixture-euna',NIGHTLY_PLAN_DOC_ID:'fixture-plan',...(separate?{HANA_FOLDER_ID:'fixture-hana',JONAH_FOLDER_ID:'fixture-jonah'}:{}),...props};
 const folders=new Map(),calls=[],writes=[],logs=[],documents=new Map([['fixture-plan',{text,sharing,trashed,mime}]]);
 let held=busy;const p={getProperty:k=>values[k]??null,setProperty:(k,v)=>{writes.push(['property',k]);values[k]=v;return p;}};
 function folder(id){if(!folders.has(id))folders.set(id,new Map());return folders.get(id);}
 function file(data,id){return {getId:()=>id,getMimeType:()=>data.mime||'text',isTrashed:()=>!!data.trashed,getSharingAccess:()=>data.sharing||'PRIVATE',getBlob:()=>({getDataAsString:()=>data.text}),setContent:s=>{writes.push(['content',id]);data.text=s;},setTrashed:()=>{throw Error('Unexpected deletion');}};}
 const iterator=arr=>{let i=0;return {hasNext:()=>i<arr.length,next:()=>{assert(i<arr.length);return arr[i++];}};};
 class FixedDate extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const context=vm.createContext({Date:FixedDate,console:{log:s=>logs.push(s)},PropertiesService:{getScriptProperties:()=>p},MimeType:{GOOGLE_DOCS:'document',PLAIN_TEXT:'text'},
  DriveApp:{Access:{PRIVATE:'PRIVATE'},getFolderById:id=>{calls.push(['folder',id]);if(!id)throw Error('No folder');return {getFilesByName:name=>{calls.push(['file',id,name]);let d=folder(id).get(name);return iterator(d?[file(d,id+'/'+name)]:[]);},createFile:(name,text,mime)=>{writes.push(['create',id,name]);const d={text,mime};folder(id).set(name,d);return file(d,id+'/'+name);}};},
   getFileById:id=>{calls.push(['docfile',id]);const d=documents.get(id);if(!d)throw Error('Unknown document');return file(d,id);},
   searchFiles:q=>{calls.push(['search',q]);return iterator([...documents].map(([id,d])=>file(d,id)));}},
  DocumentApp:{openById:id=>{calls.push(['doc',id]);if(docsError)throw Error('Docs permission or quota failed');const d=documents.get(id);if(!d)throw Error('Missing document');return {getBody:()=>({getText:()=>d.text})};}},
  LockService:{getScriptLock:()=>{calls.push(['lock']);return {tryLock:ms=>{calls.push(['tryLock',ms]);if(held)return false;held=true;return true;},releaseLock:()=>{calls.push(['releaseLock']);held=false;}};}},
  Utilities:{formatDate:(date,zone,format)=>{assert.equal(format,'yyyy-MM-dd');return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}},
  ContentService:{MimeType:{JSON:'application/json'},createTextOutput:text=>({getContent:()=>text,setMimeType(m){assert.equal(m,'application/json');return this;}})}
 });vm.runInContext(source,context,{filename:'relay.gs',timeout:1000});
 return {context,values,folders,calls,writes,logs,documents,
  request:body=>JSON.parse(context.doPost({postData:{contents:JSON.stringify(body)}}).getContent()),
  raw:contents=>JSON.parse(context.doPost({postData:{contents}}).getContent()),
  get:()=>JSON.parse(context.doGet().getContent()),
  dump:()=>Object.fromEntries([...folders].sort().map(([id,f])=>[id,Object.fromEntries([...f].sort())]))};
}
const post=(e,b)=>e.request({secret:SECRET,reason:'synthetic test',backup:clone(b)});
const read=e=>e.request({secret:SECRET,action:'readNextSession'});
const filename={Euna:'euna-mochi-latest.json',Hana:'hana-learning-latest.json',Jonah:'jonah-pokemath-latest.json'};
function value(e,child,separate=true){const id=separate?{Euna:'fixture-euna',Hana:'fixture-hana',Jonah:'fixture-jonah'}[child]:'fixture-euna';return JSON.parse(e.folders.get(id).get(filename[child]).text);}

test('Pinned shared-family template baseline matches the repository source',()=>{const b=Buffer.from(original);assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${b.length}\0`),b])).digest('hex'),'550a1e88f5e0409f734b24459188e9e947470c41');});
test('All original upload validators, merge helpers and filenames remain byte-for-byte unchanged',()=>{assert(corrected.includes(original.slice(original.indexOf('function validateHana_'))));const a=original.slice(original.indexOf('  var b=body.backup'),original.indexOf('function validateHana_'));assert(corrected.includes(a));});
for(const child of ['Hana','Jonah'])test(`Negative control: supplied Euna-only relay rejects ${child}`,()=>{assert.equal(post(env(eunaOnly),backups()[child]).error,'Invalid Mochi backup.');});
test('Negative control: old family relay does not understand nightly reads',()=>{assert.equal(read(env(original)).error,'Unsupported learning backup.');});
for(const separate of [true,false]) for(const child of ['Euna','Hana','Jonah'])test(`${child}: upload, response and stored JSON match original (${separate?'separate':'shared'} folders)`,()=>{const a=env(original,{separate}),b=env(corrected,{separate});assert.deepEqual(post(b,backups()[child]),post(a,backups()[child]));assert.deepEqual(b.dump(),a.dump());assert.deepEqual(b.writes,a.writes);assert.deepEqual(b.calls,a.calls);});
for(const separate of [true,false])test(`Interleaved plan reads and all three uploads preserve output (${separate?'separate':'shared'} folders)`,()=>{const a=env(original,{separate}),b=env(corrected,{separate}),bs=backups();for(let i=0;i<12;i++)for(const child of ['Hana','Euna','Jonah']){assert(read(b).ok);assert.deepEqual(post(b,bs[child]),post(a,bs[child]));assert(read(b).ok);}assert.deepEqual(b.dump(),a.dump());assert.deepEqual(b.writes,a.writes);});
for(const direction of ['older','same','newer'])test(`Hana ${direction} snapshot handling is unchanged`,()=>{const a=env(original),b=env(corrected),first=backups().Hana;post(a,first);post(b,first);const next=clone(first);next.exportedAt+=(direction==='older'?-1000:direction==='newer'?1000:0);next.learning.events.push({id:'synthetic-h-2'});assert.deepEqual(post(b,next),post(a,next));assert.deepEqual(b.dump(),a.dump());if(direction!=='newer')assert.equal(value(b,'Hana').learning.events.length,1);});
test('Jonah: late device adds new sessions without overwriting higher existing revisions or newer metadata',()=>{const a=env(original),b=env(corrected),first=backups().Jonah;post(a,first);post(b,first);const late=clone(first);late.exportedAt='2026-10-07T01:00:00.000Z';late.build=1;late.sessions.synthetic1.rev=1;late.sessions.synthetic1.questions={old:{}};late.sessions.synthetic2={id:'synthetic2',rev:1,days:{},questions:{new:{}}};assert.deepEqual(post(b,late),post(a,late));assert.deepEqual(b.dump(),a.dump());const out=value(b,'Jonah');assert.equal(out.sessions.synthetic1.rev,2);assert(out.sessions.synthetic2);assert.equal(out.build,85);});
test('Jonah: higher session revision replaces only that session',()=>{const e=env(corrected),b=backups().Jonah;post(e,b);b.sessions.synthetic1.rev=3;b.sessions.synthetic1.questions.q2={correct:false};post(e,b);assert.equal(value(e,'Jonah').sessions.synthetic1.rev,3);assert(value(e,'Jonah').sessions.synthetic1.questions.q2);});
test('Hana and Jonah credential allowlists remain intact',()=>{const e=env(corrected);for(const child of ['Hana','Jonah']){post(e,backups()[child]);assert(!Object.hasOwn(value(e,child),'credentials'));}});
test('Euna: existing backup, learning state and nightly receipt are copied without mutation',()=>{const e=env(corrected),b=backups().Euna;post(e,b);assert.deepEqual(value(e,'Euna'),b);});
test('Busy upload lock refuses writes and plan reads still work without taking that lock',()=>{const e=env(corrected,{busy:true});assert.equal(post(e,backups().Hana).ok,false);assert.equal(e.writes.length,0);const n=e.calls.length;assert(read(e).ok);assert(!e.calls.slice(n).some(c=>['folder','lock','tryLock','releaseLock'].includes(c[0])));});
test('Upload errors release the lock, allowing the next child to upload',()=>{const e=env(corrected);e.folders.set('fixture-hana',new Map([['hana-learning-latest.json',{text:'bad JSON',mime:'text'}]]));assert.equal(post(e,backups().Hana).ok,false);assert.equal(post(e,backups().Jonah).ok,true);assert.equal(e.calls.filter(c=>c[0]==='releaseLock').length,2);});
for(const secret of ['', 'incorrect', undefined])test(`Plan read rejects ${String(secret)} secret before any data access`,()=>{const e=env(corrected);assert.equal(e.request({secret,action:'readNextSession'}).ok,false);assert.equal(e.calls.length,0);assert.equal(e.writes.length,0);});
test('Missing configured secret rejects every operation',()=>{const e=env(corrected,{props:{MIRROR_SECRET:''}});assert.equal(read(e).ok,false);assert.equal(post(e,backups().Hana).ok,false);assert.equal(e.calls.length,0);});
test('Public GET returns service metadata only and does not access Drive',()=>{const e=env(corrected),r=e.get();assert.equal(r.service,'family-learning-mirror');assert.equal(r.relayVersion,'1.2.0');assert.equal(r.planApi,1);assert(!('plan' in r));assert.equal(e.calls.length,0);assert(!JSON.stringify(r).includes(SECRET));});
test('Nightly response matches Mochi v7.7.0 exact protocol and does not write anything',()=>{const e=env(corrected),before=clone(e.values),r=read(e);assert.equal(r.service,'mochi-drive-mirror');assert.equal(r.planApi,1);assert.equal(r.ok,true);assert.deepEqual(r.plan,plan());assert.deepEqual(e.values,before);assert.equal(e.writes.length,0);assert.deepEqual(e.calls,[['docfile','fixture-plan'],['doc','fixture-plan']]);assert.equal(e.folders.size,0);});
for(const extra of [{backup:backups().Jonah},{docId:'other-file'},{student:'Hana'},{url:'https://invalid.example'}])test(`Nightly read rejects unrelated fields: ${Object.keys(extra)[0]}`,()=>{const e=env(corrected);assert.equal(e.request({secret:SECRET,action:'readNextSession',...extra}).ok,false);assert.equal(e.calls.length,0);assert.equal(e.writes.length,0);});
test('Unknown action never falls through to uploading a supplied backup',()=>{const e=env(corrected);assert.equal(e.request({secret:SECRET,action:'overwritePlan',backup:backups().Euna}).ok,false);assert.equal(e.writes.length,0);});
for(const [name,opts] of Object.entries({noConfiguration:{props:{NIGHTLY_PLAN_DOC_ID:''}},malformed:{text:'not JSON'},publicDocument:{sharing:'ANYONE_WITH_LINK'},trashed:{trashed:true},wrongType:{mime:'text'},docsPermissionFailure:{docsError:true},oversize:{text:'x'.repeat(20001)}}))test(`Plan failure (${name}) does not affect any child's upload`,()=>{const e=env(corrected,opts);assert.equal(read(e).ok,false);assert.equal(e.writes.length,0);for(const child of ['Euna','Hana','Jonah'])assert.equal(post(e,backups()[child]).ok,true,child);});
test('Empty plan returns null without altering uploads or settings',()=>{const e=env(corrected,{text:''});assert.equal(read(e).plan,null);assert.equal(e.writes.length,0);});
const invalidPlans={
 wrongStudent:p=>p.student='Hana',newScript:p=>p.script='alert(1)',extraSubject:p=>p.subjects.jonah={},unknownStep:p=>p.subjects.maths.steps[0].url='https://invalid.example',missingSubject:p=>delete p.subjects.science,markup:p=>p.subjects.maths.focus='<script>x</script>',tooMany:p=>p.subjects.maths.steps=Array.from({length:4},()=>({kind:'practice',unit:'geo-face-pairs',phase:'apply',count:2})),invalidPhase:p=>p.subjects.maths.steps[1].phase='paper',zeroCount:p=>p.subjects.maths.steps[1].count=0,badDate:p=>p.sessionDate='2026-02-30',backwardsDate:p=>p.sessionDate='2026-10-06',badTimestamp:p=>p.generatedAt='bad time',laterSource:p=>p.sourceExportedAt='2027-01-01T00:00:00.000Z',stringRevision:p=>p.revision='1'
};
for(const [name,mutate] of Object.entries(invalidPlans))test(`Invalid plan is rejected without writes: ${name}`,()=>{const p=plan();mutate(p);const e=env(corrected,{text:JSON.stringify(p)});assert.equal(read(e).ok,false);assert.equal(e.writes.length,0);});
test('Old dated plan is not relabelled as today; the app can reject its date',()=>{const p=plan();p.sessionDate='2026-10-07';p.reviewedDate='2026-10-06';const e=env(corrected,{text:JSON.stringify(p)});assert.equal(read(e).plan.sessionDate,'2026-10-07');assert.equal(e.writes.length,0);});
test('Setup preserves existing secret/folder properties and only sets plan document ID',()=>{const e=env(corrected),before=clone(e.values);e.context.setupNightlyPlan();assert.deepEqual(e.values,before);assert.deepEqual(e.writes,[['property','NIGHTLY_PLAN_DOC_ID']]);assert(!e.logs.join('').includes(SECRET));assert.equal(e.folders.size,0);});
test('Setup fails on duplicate documents without modifying configuration',()=>{const e=env(corrected);e.documents.set('second',{text:JSON.stringify(plan()),mime:'document'});assert.throws(()=>e.context.setupNightlyPlan(),/exactly one/);assert.equal(e.writes.length,0);});
test('Read-only editor check checks all four routes without writes or leaking secrets/IDs',()=>{const e=env(corrected);for(const b of Object.values(backups()))post(e,b);const before=e.dump(),count=e.writes.length,props=clone(e.values);const r=clone(e.context.checkFamilyRelayReadOnly());assert.equal(r.deploymentVerified,false);assert(r.nightlyPlan.readable);assert(r.nightlyPlan.datedForToday);for(const c of ['Euna','Hana','Jonah'])assert.match(r.uploads[c].status,/recognised/);assert.deepEqual(e.dump(),before);assert.equal(e.writes.length,count);assert.deepEqual(e.values,props);assert(!e.logs.join('').includes(SECRET));assert(!e.logs.join('').includes('fixture-plan'));});
test('Malformed/missing backup requests reject safely',()=>{for(const raw of ['', '{', 'null','[]','{}']){const e=env(corrected);assert.equal(e.raw(raw).ok,false);assert.equal(e.writes.length,0);}});
test('Each upload changes only its own latest and weekly files, including a shared folder',()=>{const e=env(corrected,{separate:false});for(const b of Object.values(backups()))post(e,b);for(const child of ['Euna','Hana','Jonah']){const before=e.dump()['fixture-euna'];post(e,backups()[child]);const after=e.dump()['fixture-euna'];for(const name of Object.keys(before)){if(!name.startsWith(filename[child].replace('-latest.json','-')))assert.deepEqual(after[name],before[name]);}}});
test('Chicago week naming matches original around DST and year rollover',()=>{for(const at of ['2026-11-01T05:59:00Z','2026-11-01T07:01:00Z','2027-01-01T00:30:00Z','2027-01-04T06:01:00Z']){const options={now:Date.parse(at)},a=env(original,options),b=env(corrected,options);assert.deepEqual(post(b,backups().Euna),post(a,backups().Euna));assert.deepEqual(b.dump(),a.dump());}});

function siblingPlan(student){const p=plan();p.student=student;p.id=student.toLowerCase()+'-nightly-2026-10-08';p.subjects={maths:{focus:'Practise the next small step.',skills:student==='Hana'?['p3-place']:['sub']}};if(student==='Jonah')p.subjects.reading={focus:'Blend sounds into a word.',sounds:['s','a'],words:['sat']};return p;}
function siblingEnv(student,options={}){const e=env(corrected,options),key=student.toUpperCase()+'_NIGHTLY_PLAN_DOC_ID';e.values[key]='fixture-'+student;e.documents.set('fixture-'+student,{mime:'document',text:JSON.stringify(siblingPlan(student))});return e;}
const siblingRead=(e,student,extra={})=>e.request({action:'read'+student+'NextSession',secret:SECRET,...extra});
for(const student of ['Hana','Jonah']){
 test(student+': fixed private route returns only that child without writes, locks or settings changes',()=>{const e=siblingEnv(student),before=clone(e.values);const r=siblingRead(e,student);assert.equal(r.ok,true);assert.equal(r.service,'family-learning-mirror');assert.equal(r.student,student);assert.deepEqual(r.plan,siblingPlan(student));assert.deepEqual(e.values,before);assert.equal(e.writes.length,0);assert.deepEqual(e.calls,[['docfile','fixture-'+student],['doc','fixture-'+student]]);assert(read(e).ok);});
 test(student+': missing configuration never falls back to another child',()=>{const e=env(corrected);assert.equal(siblingRead(e,student).ok,false);assert.equal(e.calls.length,0);for(const b of Object.values(backups()))assert(post(e,b).ok);});
 for(const extra of [{docId:'fixture-plan'},{student:'Euna'},{backup:backups().Euna},{secret:'wrong'}])test(student+': rejects injected '+Object.keys(extra)[0]+' before data access',()=>{const e=siblingEnv(student);assert.equal(siblingRead(e,student,extra).ok,false);assert.equal(e.calls.length,0);assert.equal(e.writes.length,0);});
 for(const issue of ['wrong-child','bad-json','public','trashed','oversized','unknown-field','bad-date','duplicate-skill','script','too-many','empty','wrong-subject'])test(student+': rejects '+issue+'; all uploads still match the original',()=>{const e=siblingEnv(student),d=e.documents.get('fixture-'+student),p=siblingPlan(student);
  if(issue==='wrong-child')p.student='Euna';if(issue==='unknown-field')p.script='alert(1)';if(issue==='bad-date')p.sessionDate='2026-02-30';if(issue==='duplicate-skill')p.subjects.maths.skills.push(p.subjects.maths.skills[0]);if(issue==='script')p.subjects.maths.focus='<img>';if(issue==='too-many')p.subjects.maths.skills=['a','b','c','d'];if(issue==='empty')p.subjects.maths.skills=[];if(issue==='wrong-subject')p.subjects.science={};
  d.text=issue==='bad-json'?'{':issue==='oversized'?'x'.repeat(20001):JSON.stringify(p);if(issue==='public')d.sharing='ANYONE';if(issue==='trashed')d.trashed=true;
  assert.equal(siblingRead(e,student).ok,false);assert.equal(e.writes.length,0);const originalEnv=env(original);for(const b of Object.values(backups()))assert.deepEqual(post(e,b),post(originalEnv,b));assert.deepEqual(e.dump(),originalEnv.dump());
 });
}
test('All three plan reads are isolated when properties are accidentally crossed',()=>{const e=siblingEnv('Hana');e.values.JONAH_NIGHTLY_PLAN_DOC_ID=e.values.HANA_NIGHTLY_PLAN_DOC_ID;assert(siblingRead(e,'Hana').ok);assert.equal(siblingRead(e,'Jonah').ok,false);assert(read(e).ok);assert.equal(e.writes.length,0);});
test('Mixed sibling reads and uploads preserve historical sessions and file identities in a shared folder',()=>{const e=siblingEnv('Hana',{separate:false}),a=env(original,{separate:false});e.values.JONAH_NIGHTLY_PLAN_DOC_ID='fixture-Jonah';e.documents.set('fixture-Jonah',{mime:'document',text:JSON.stringify(siblingPlan('Jonah'))});for(let i=0;i<8;i++)for(const child of ['Euna','Hana','Jonah']){const b=backups()[child];assert.deepEqual(post(e,b),post(a,b));assert(read(e).ok);assert(siblingRead(e,'Hana').ok);assert(siblingRead(e,'Jonah').ok);}assert.deepEqual(e.dump(),a.dump());assert.deepEqual(e.writes,a.writes);});

for(const student of ["Hana","Jonah"])test(student+": existing JSON null placeholder is a successful empty plan, with no writes",()=>{const e=siblingEnv(student);e.documents.get("fixture-"+student).text="null";const r=siblingRead(e,student);assert.equal(r.ok,true);assert.equal(r.plan,null);assert.equal(e.writes.length,0);});
